Repository topoteretes/cognee, pull requests merged in 2025-09, with the labels that each got.

#1338 fix: temporal retriever return values
  cognee/modules/retrieval/temporal_retriever.py
Labels: run-checks

#1420 fix: combined context search
  cognee-frontend/src/ui/elements/Notebook/Notebook.tsx
  cognee/modules/search/methods/search.py
  cognee/modules/search/utils/prepare_search_result.py
  cognee/modules/search/utils/transform_context_to_graph.py
  cognee/modules/search/utils/transform_insights_to_graph.py
Labels: run-checks

#1422 Merge dev into main
  cognee-frontend/src/ui/elements/Notebook/Notebook.tsx
  cognee/api/v1/search/search.py
  cognee/infrastructure/databases/vector/embeddings/OllamaEmbeddingEngine.py
  cognee/modules/search/methods/search.py
  cognee/modules/search/utils/prepare_search_result.py
  cognee/modules/search/utils/transform_context_to_graph.py
  cognee/modules/search/utils/transform_insights_to_graph.py
  cognee/tasks/temporal_graph/models.py
  cognee/tests/cli_tests/cli_unit_tests/test_cli_main.py
  cognee/tests/test_temporal_graph.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: core-team

#1418 refactor: make cypher query optional
  .env.template
  cognee/modules/search/methods/get_search_type_tools.py
Labels: core-team

#1437 This commit is realated to issue #1436 and I removed that bug.
  cognee/infrastructure/databases/graph/kuzu/adapter.py
Labels: community-contribution

#1305 fix: Cog 2826 clean up poetry
  .github/actions/cognee_setup/action.yml
  .github/workflows/basic_tests.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/test_s3_file_storage.yml
  cognee/api/client.py
  cognee/eval_framework/modal_eval_dashboard.py
  cognee/infrastructure/data/utils/extract_keywords.py
  cognee/infrastructure/databases/relational/create_relational_engine.py
  cognee/infrastructure/databases/vector/create_vector_engine.py
  cognee/infrastructure/databases/vector/lancedb/LanceDBAdapter.py
  cognee/infrastructure/databases/vector/pgvector/PGVectorAdapter.py
  cognee/infrastructure/files/storage/S3FileStorage.py
  cognee/infrastructure/files/utils/open_data_file.py
  cognee/infrastructure/llm/config.py
  cognee/infrastructure/llm/structured_output_framework/baml/baml_src/extraction/acreate_structured_output.py
  cognee/modules/ingestion/data_types/TextData.py
  cognee/modules/visualization/cognee_network_visualization.py
  cognee/shared/utils.py
  cognee/tasks/graph/infer_data_ontology.py
  poetry.lock
  pyproject.toml
  uv.lock
Labels: core-team

#1457 feat: cors issue if frontend runs on any port other than 3000
  .env.template
  cognee/api/client.py
Labels: run-checks, core-team

#1473 fix: limit onnxruntime version
  poetry.lock
  pyproject.toml
  uv.lock
Labels: run-checks, core-team

#1472 feat: start mcp in ui cli command
  cognee-frontend/src/ui/Layout/Header.tsx
  cognee-frontend/src/ui/elements/StatusDot.tsx
  cognee-frontend/src/ui/elements/index.ts
  cognee-frontend/src/utils/fetch.ts
  cognee-mcp/entrypoint.sh
  cognee-mcp/pyproject.toml
  cognee-mcp/src/server.py
  cognee/api/v1/ui/__init__.py
  cognee/api/v1/ui/ui.py
  cognee/cli/_cognee.py
  examples/start_ui_example.py
Labels: core-team

#1466 docs: Multi user authorization example
  .github/workflows/examples_tests.yml
  cognee/api/v1/permissions/routers/get_permissions_router.py
  cognee/modules/users/roles/methods/create_role.py
  cognee/modules/users/tenants/methods/create_tenant.py
  examples/python/permissions_example.py
Labels: core-team

#1475 feat: Add update endpoint to Cognee [COG-3016]
  cognee/api/client.py
  cognee/api/v1/update/__init__.py
  cognee/api/v1/update/routers/__init__.py
  cognee/api/v1/update/routers/get_update_router.py
  cognee/api/v1/update/update.py
Labels: core-team

#1464 Feature/windows compatibility fixes
  cognee-frontend/src/app/(graph)/GraphVisualization.tsx
  cognee-frontend/src/utils/fetch.ts
  cognee/api/health.py
  cognee/api/v1/cloud/routers/get_checks_router.py
  cognee/api/v1/ui/ui.py
  cognee/cli/_cognee.py
  cognee/infrastructure/llm/prompts/read_query_prompt.py
  cognee/infrastructure/llm/prompts/test.txt
  cognee/tests/test_cognee_server_start.py
  pyproject.toml
Labels: community-contribution

#1486 fix: resolve formatting issue
  cognee/api/v1/cloud/routers/get_checks_router.py
Labels: core-team
